name: Desplegar

on:
  workflow_dispatch:

jobs:
  vpn_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          if [[ -z "${{ secrets.VPN_USERNAME }}" ]]; then echo "VPN_USERNAME no está definido"; fi
          if [[ -z "${{ secrets.VPN_PASSWORD }}" ]]; then echo "VPN_PASSWORD no está definido"; fi
          if [[ -z "${{ secrets.VPN_IP }}" ]]; then echo "VPN_IP no está definido"; fi


      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn openvpn-systemd-resolved

      - name: Configurar la VPN
        working-directory: .github/workflows
        run: |
          echo "${{ secrets.VPN_CA }}" | base64 --decode > ca.crt
          ls
          echo "${{ secrets.VPN_USERNAME }}" > credenciales.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> credenciales.txt
          sed -i "s/REPLACE_VPN_IP/${{ secrets.VPN_IP }}/" vpn-pve.conf
          sed -i "s/REPLACE_VPN_PORT/${{ secrets.VPN_PORT }}/" vpn-pve.conf
          cat vpn-pve.conf 

      - name: Connect to VPN
        working-directory: .github/workflows      
        run: sudo openvpn --config .github/workflows/vpn-pve.conf --daemon --log openvpn.log 

      - name: Wait for VPN to establish
        run: sleep 10

      - name: Test Connection
        working-directory: .github/workflows
        run: sudo cat openvpn.log 

      - name: Test Connection
        run: ping 192.168.59.104

      - name: Run remote script
        working-directory: .github/workflows      
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_ID_RSA }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ./id_rsa
          chmod 600 ./id_rsa
          ssh -i ./id_rsa lgonzalez@192.168.59.104 "./fechas.sh"
