name: Desplegar

on:
  workflow_dispatch:

jobs:
  vpn_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 

      - name: Configurar la VPN
        working-directory: .github/workflows
        run: |
          sudo apt-get update && sudo apt-get install -y openvpn openvpn-systemd-resolved
          echo "${{ secrets.VPN_CA }}" | base64 --decode > ca.crt
          echo "${{ secrets.VPN_USERNAME }}" > credenciales.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> credenciales.txt
          sed -i "s/REPLACE_VPN_IP/${{ secrets.VPN_IP }}/" vpn-pve.conf
          sed -i "s/REPLACE_VPN_PORT/${{ secrets.VPN_PORT }}/" vpn-pve.conf 

      - name: Connect to VPN
        working-directory: .github/workflows      
        run: sudo openvpn --config vpn-pve.conf --daemon --log openvpn.log 

      - name: Wait for VPN to establish
        run: sleep 10

      - name: Test Connection
        working-directory: .github/workflows
        run: sudo cat openvpn.log 

      - name: Test Connection
        run: ping -c 2 192.168.59.104

      - name: Run remote script
        working-directory: .github/workflows      
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_ID_RSA }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ./id_rsa
          chmod 600 ./id_rsa
          ssh -i ./id_rsa -o StrictHostKeyChecking=no  ${{ secrets.VPN_USERNAME }}@192.168.59.104 'rm -rf DesplegarFacturasDocker'        
          ssh -i ./id_rsa -o StrictHostKeyChecking=no  ${{ secrets.VPN_USERNAME }}@192.168.59.104 'git clone https://github.com/lgonzalezmislata/DesplegarFacturasDocker.git'
          ssh -i ./id_rsa -o StrictHostKeyChecking=no  ${{ secrets.VPN_USERNAME }}@192.168.59.104 'cd DesplegarFacturasDocker && ./deploy.sh'